USE MASTER
GO

IF DB_ID ('EL_ZAPATO_ROTO') IS NOT NULL
	ALTER DATABASE EL_ZAPATO_ROTO SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
	DROP DATABASE IF EXISTS EL_ZAPATO_ROTO;
GO

CREATE DATABASE EL_ZAPATO_ROTO
GO

USE EL_ZAPATO_ROTO

GO

CREATE TABLE PRODUCTO
(
	NOMBRE_PRODUCTO VARCHAR(50) PRIMARY KEY NOT NULL,
	PRESENTACION VARCHAR(100) NOT NULL,
	VALOR MONEY NOT NULL,
	ID_INVENTARIO BIGINT NOT NULL
)
GO

CREATE TABLE INVENTARIO
(
	ID_INVENTARIO BIGINT IDENTITY PRIMARY KEY NOT NULL,
	ID_MOVIMIENTO TINYINT NOT NULL,
	FECHA DATE NOT NULL,
	CANTIDAD INT NOT NULL
)
GO

CREATE TABLE MOVIMIENTO
(
	ID_MOVIMIENTO TINYINT IDENTITY PRIMARY KEY NOT NULL,
	NOMBRE_MOVIMIENTO VARCHAR(7) NOT NULL
)
GO

CREATE TABLE FACTURACION_PRODUCTO
(
	NUMERO_FACTURACION BIGINT NOT NULL,
	NOMBRE_PRODUCTO VARCHAR(50) NOT NULL,
	IMPUESTO MONEY NOT NULL,
	DESCUENTO MONEY NOT NULL,
	PRIMARY KEY(NUMERO_FACTURACION,NOMBRE_PRODUCTO)
)
GO

CREATE TABLE FACTURACION
(
	NUMERO_FACTURACION BIGINT IDENTITY PRIMARY KEY NOT NULL,
	IDENTIFICACION_CLIENTE BIGINT NOT NULL,
	VALOR_PAGAR MONEY NOT NULL
)
GO

CREATE TABLE CLIENTE
(
	IDENTIFICACION_CLIENTE BIGINT PRIMARY KEY NOT NULL,
	NOMBRE_CLIENTE VARCHAR(50) NOT NULL,
	ID_PAIS INT NOT NULL
)
GO

CREATE TABLE PAIS
(
	ID_PAIS INT IDENTITY PRIMARY KEY,
	NOMBRE VARCHAR(20) NOT NULL
)

ALTER TABLE INVENTARIO ADD FOREIGN KEY (ID_MOVIMIENTO) REFERENCES MOVIMIENTO(ID_MOVIMIENTO);
GO
ALTER TABLE PRODUCTO ADD FOREIGN KEY (ID_INVENTARIO) REFERENCES INVENTARIO(ID_INVENTARIO);
GO
ALTER TABLE FACTURACION_PRODUCTO ADD FOREIGN KEY (NUMERO_FACTURACION) REFERENCES FACTURACION(NUMERO_FACTURACION);
GO
ALTER TABLE FACTURACION_PRODUCTO ADD FOREIGN KEY (NOMBRE_PRODUCTO) REFERENCES PRODUCTO(NOMBRE_PRODUCTO);
GO
ALTER TABLE FACTURACION ADD FOREIGN KEY (IDENTIFICACION_CLIENTE) REFERENCES CLIENTE(IDENTIFICACION_CLIENTE);
GO
ALTER TABLE CLIENTE ADD FOREIGN KEY (ID_PAIS) REFERENCES PAIS(ID_PAIS);
GO